services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT_SSL:-443}:443"
    volumes:
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./docker/laravel:/var/www/html
      - /etc/letsencrypt/live/dev.nz748225.tw1.su/fullchain.pem:/etc/letsencrypt/live/dev.nz748225.tw1.su/fullchain.pem
      - /etc/letsencrypt/live/dev.nz748225.tw1.su/privkey.pem:/etc/letsencrypt/live/dev.nz748225.tw1.su/privkey.pem
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    entrypoint: /bin/sh -c "envsubst '\$APP_DOMAIN' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - laravel_app
    networks:
      - app-network

  laravel_app:
    image: php:8.2-fpm
    build:
      context: ./docker/laravel
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./docker/laravel:/var/www/html
      - ./docker/mysql/ssl:/etc/mysql/ssl:ro
      - ./docker/laravel/.my.cnf:/etc/mysql/my.cnf/
    environment:
      - APP_ENV=local
    networks: 
      - app-network
    entrypoint: ["php-fpm", "-F"] 
    
  composer:
    image: composer:2.8
    container_name: composer
    working_dir: /var/www/html
    volumes: 
      - ./docker/laravel:/var/www/html
    networks:
      - app-network
    entrypoint: ["tail", "-f", "/dev/null"]

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT:-3306}:3306" 
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/ssl:/etc/mysql/ssl
    networks:
      - app-network
      
  node:
    image: node:20
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./docker/laravel:/var/www/html
    environment:
      - VITE_APP_URL=https://dev.nz748225.tw1.su
    command: sh -c "npm install && npm run build"
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge